### PR TITLE
Include "hidden" files to backup

### PR DESCRIPTION
**Pull request by N1ebieski**
Files with a dot at the beginning of the name like .htaccess, .env, .git etc

### CODE REVIEW

**Comment by myvesta** [comment]
but I see dot files in backup even without this fix?
image
image

**Comment by N1ebieski** [comment]
Only if file is in a public/public_html folder. Check dot files that are one level above the public folder.

**Comment by myvesta** [comment]
Thank you very much :)

**Comment by myvesta** [comment]
@N1ebieski please check https://forum.myvestacp.com/viewtopic.php?t=747

**Comment by N1ebieski** [comment]
https://forum.myvestacp.com/viewtopic.php?p=2310#p2310

**Pull request merged**
