### PR TITLE
biiiiiiiig update from official vesta

### PR DESCRIPTION
**Pull request by myvesta**

### CODE REVIEW

**Comment by darkworks** [comment]
i have installed it because i like the secret login url feature of it  , just wondering that myvesta support autoupdate or not , or on update it will reset to official version ?

**Comment by dpeca** [comment]
@darkworks 
Auto-update is fully supported, just like in official Vesta - but - to be honest - i must check how Vesta check for new version. I will check later.

However, `apt upgrade` will always get updates from myVesta - because we have our own apt repo :)
```
# cat /etc/apt/sources.list.d/vesta.list
deb http://apt.vesta.hostingpanel.dev/buster/ buster vesta

```

**Comment by dpeca** [comment]
@darkworks 
Yes, auto-update will works, because it is checking apt too...
https://github.com/myvesta/vesta/blob/master/bin/v-update-sys-vesta#L52

**Comment by dpeca** [comment]
@darkworks 
but ''Updates'' page will actually see ''newest release number'' from official vesta - https://github.com/myvesta/vesta/blob/master/bin/v-list-sys-vesta-updates#L64
Will fix that, but however, nothing depends on that number, auto-update will happen if I push v26 on myvesta repo.

**Comment by darkworks** [comment]
good to hear

**Comment by suricloud** [comment]
How to install this on centos 7 or Ubuntu 18 ?

**Comment by dpeca** [comment]
> 
> 
> How to install this on centos 7 or Ubuntu 18 ?

There is no way to do it.
This fork supports only Debian.
Read why - https://github.com/myvesta/vesta/blob/master/README.md

**Comment by dpeca** [comment]
@shahidirfan100
> 
> 
> Where is the location of this file?

what file?

**Comment by darkworks** [comment]
@dpeca  i have restored my original vesta backup on myvesta installation but my website which i using htaccess rules is not working on my vesta i checked the web templates its different from the original vesta

original vesta cp
image

my vesta cp
image

so i wonder can we add default templates of vestacp , because htaccess php powered rules sites are not working ok with this php-fpm template , as i have placed html test file in it and it opened but  other not working

**Comment by dpeca** [comment]
@darkworks
try with "hosting-legacy" proxy template

**Pull request merged**
